## IMPORTANT ## 
# the environment variables need to be set for this to work

version: '3.8'
services:
  web:
    build: .
    image: ${REGISTRY}/${IMAGE_NAME}/web:${IMAGE_TAG}
    # set environment variable
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CLERK_SECRET=${CLERK_SECRET}
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
