name: Deploy to DigitalOcean Droplet

on:
  workflow_run:
    workflows: ["Docker"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check outcome of triggered workflow
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: |
          echo "The triggering workflow failed. Deployment will not proceed."
          exit 1
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to Droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22 # Default SSH port, adjust if different
          script: |
            docker login ghcr.io -u ${{ github.actor }} --password-stdin <<< ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}:latest
            # Replace or restart your container below. This is just an example.
            docker stop argo-backend || true
            docker rm argo-backend || true
            docker run -d --name argo-backend ghcr.io/${{ github.repository }}:latest
